### ISSUE TITLE
FirmwareManager not working with P1s

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/spark-protocol#40]
```
Cannot read property 'binaryFileName' of undefined TypeError: Cannot read property 'binaryFileName' of undefined
    at _callee$ (/opt/particle/brewskey/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:177:104)
    at tryCatch (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/opt/particle/brewskey/spark-server/node_modules/core-js/library/modules/_export.js:35:28)
    at Function.<anonymous> (/opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Function.getOtaSystemUpdateConfig (/opt/particle/brewskey/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:192:18)
    at DeviceServer._callee4$ (/opt/particle/brewskey/spark-server/node_modules/spark-protocol/dist/server/DeviceServer.js:446:60)
    at tryCatch (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:297:24)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by jlkalberer** [comment]
@wdimmit - are you still seeing this? 

I added more logging but I can't reproduce this with a P1.  The OTA system update is working fine for me.

**Comment by wdimmit** [comment]
I am no longer seeing this.  By "OTA System" do you mean just POST'ing the firmware to a device, or this new functionality you've built?

**Comment by jlkalberer** [comment]
Nope, this is new.  When you run `npm install` we pull down the latest system firmware images from the `spark\firmware` repository.  

So, the system firmware has a built-in check that determines if the system firmware is greater than the application firmware.  If the app firmware is built against a newer version, the device goes in to safe mode.

We updated the server so when the device goes in to safemode like this, the server will start sending over the system updates
