### ISSUE TITLE
Errors on device reconnection after server shutdown

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-protocol#41]
If I shutdown the server with CTRL-C, I see a stream of the following error as the devices reconnect:

Error: No device state!
    at Device._callee5$ (/opt/particle/brewskey/spark-server/node_modules/spark-protocol/dist/clients/Device.js:661:21)
    at tryCatch (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/opt/particle/brewskey/spark-server/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /opt/particle/brewskey/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13

I have not discovered any failures stemming from this error.

**Comment by jlkalberer** [comment]
Just to confirm this is a P1 running v0.6.0 firmware?  I'm guessing that the function state is null when this is called:
https://github.com/Brewskey/spark-protocol/blob/dev/src/clients/Device.js#L602-L603

Can you send me a test firmware for your P1 over slack?

**Comment by AntonPuko** [comment]
i've got this with my photon, too

**Comment by jlkalberer** [comment]
@wdimmit @AntonPuko - anyone still seeing this?

**Comment by AntonPuko** [comment]
err... I still see this sometimes

**Comment by jlkalberer** [comment]
Yeah, I just got it to happen but I added some code that *should* fix it.

The issue is that when we call `Describe` it sends back two messages in the 0.6.0 firmware.  Sometimes we can't get the second listener attached before the describe message is processed on the server.

I added some code so it will retry a few times to get the function state.
